### 1. LOGOWANIE (Pobieranie tokena) ABY TO WSZYSTKO DZIAŁAŁO TRZEBA MIEĆ WTYCZKĘ REST CLIENT
# Kliknij "Send Request" poniżej, żeby dostać token.
POST http://localhost:8000/api/token/
Content-Type: application/json

{
    "email": "streamer_1@example.com",
    "password": "Test1234!"
}

###
### 2. TEST UPRAWNIEŃ (Jako Streamer)
# SKOPIUJ 'access' z odpowiedzi powyżej i WKLEJ go zamiast <TWOJ_TOKEN>
GET http://localhost:8000/api/tax-calc/?amount=100
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc3Mzg5NDY3LCJpYXQiOjE3NzczODg1NjcsImp0aSI6IjhiMjY5ZDgyYTJiMDQwMDU4NmQ2ZGVkN2UzZDUwNDliIiwidXNlcl9pZCI6MSwicm9sZSI6InN0cmVhbWVyIiwidXNlcm5hbWUiOiJzdHJlYW1lcl8xIn0.Bnd53cLkNFr3FNgEQQexI31dhcfxgQdMlP7byYRhYzs