### 1. LOGOWANIE (Pobieranie tokena) ABY TO WSZYSTKO DZIAŁAŁO TRZEBA MIEĆ WTYCZKĘ REST CLIENT
# Kliknij "Send Request" poniżej, żeby dostać token.
POST http://localhost:8000/api/token/
Content-Type: application/json

{
    "email": "streamer_1@example.com",
    "password": "Test1234!"
}

###

### 2. TEST UPRAWNIEŃ (Jako Streamer)
# SKOPIUJ 'access' z odpowiedzi powyżej i WKLEJ go zamiast <TWOJ_TOKEN>
GET http://localhost:8000/api/test-streamer/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc2Nzc0ODM0LCJpYXQiOjE3NzY3NzM5MzQsImp0aSI6IjZjMTQ2NWQ0OTUwODRhOGFiYTI0MWY1ZWRhYzFjMzdlIiwidXNlcl9pZCI6MTksInJvbGUiOiJzdHJlYW1lciIsInVzZXJuYW1lIjoic3RyZWFtZXJfMSJ9.kBw992Lwbu6TovEutpupNAohHieLkqOuxhGbz_z_C9Q

### 3. TEST - Live data aukcji (podmień ID na istniejące)
GET http://localhost:8000/api/v1/auctions/1/live-data/

###

### 4. TEST - Buy Now (podmień ID na aukcję typu buy_now lub hybrid)
POST http://localhost:8000/api/v1/auctions/1/buy-now/
Content-Type: application/json