# Generated by Django 6.0.3 on 2026-05-19 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
    ]
