# Generated by Django 6.0.3 on 2026-04-19 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardbiduser',
            name='username',
        ),
    ]
