# Generated by Django 6.0.3 on 2026-04-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_cardbiduser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cardbiduser',
            managers=[
            ],
        ),
    ]
