# Generated by Django 6.0.3 on 2026-04-19 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_cardbiduser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardbiduser',
            name='username',
        ),
    ]
