# Generated by Django 6.0.3 on 2026-04-20 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_cardbiduser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('active', 'Aktywna'), ('cancelled', 'Anulowana'), ('ended', 'Zakończona')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='auctionslot',
            name='status',
            field=models.CharField(choices=[('active', 'Teraz'), ('finished', 'Zakończone'), ('pending', 'W kolejce')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='cardbiduser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('buyer', 'Kupujący'), ('seller', 'Sprzedający'), ('streamer', 'Streamer')], default='buyer', max_length=10),
        ),
        migrations.AlterField(
            model_name='streamroom',
            name='streamer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stream_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
