# Generated by Django 6.0.3 on 2026-04-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auction_status_alter_auctionslot_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardbiduser',
            name='username',
            field=models.CharField(default='placeholder', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
