# Generated by Django 6.0.3 on 2026-05-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_country_cardbiduser_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardbiduser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
