# Generated by Django 6.0.3 on 2026-05-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_populate_countries_and_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='min_increment',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='auctionslot',
            name='status',
            field=models.CharField(choices=[('active', 'Aktywna'), ('finished', 'Zakończona'), ('pending', 'Oczekująca')], default='pending', max_length=10),
        ),
    ]
