# Generated by Django 6.0.3 on 2026-05-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auction_min_increment_alter_auctionslot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionslot',
            name='is_opened',
            field=models.BooleanField(default=False, help_text='Indicates whether the physical package/card has been opened on the stream'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='auction_type',
            field=models.CharField(choices=[('bidding', 'Only Bidding'), ('buy_now', 'Only Buy Now'), ('hybrid', 'Bidding + Buy Now')], default='bidding', max_length=10),
        ),
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('ended', 'Ended')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='auctionslot',
            name='order',
            field=models.PositiveIntegerField(help_text='Number of the slot (e.g., 1, 2, 3...)'),
        ),
        migrations.AlterField(
            model_name='auctionslot',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('finished', 'Finished'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='cardbiduser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('buyer', 'Buyer'), ('seller', 'Seller'), ('streamer', 'Streamer')], default='buyer', max_length=10),
        ),
    ]
