# Generated by Django 6.0.3 on 2026-03-29 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aukcja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200)),
                ('kategoria', models.CharField(choices=[('Mangi', 'Mangi'), ('Gry', 'Gry'), ('Kreskówki', 'Kreskówki'), ('Sport', 'Sport')], max_length=50)),
                ('cena_aktualna', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rzadkosc', models.CharField(max_length=50)),
                ('sprzedawca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
