# Generated by Django 6.0.3 on 2026-03-29 13:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aukcje', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aukcja',
            options={'verbose_name': 'Aukcja', 'verbose_name_plural': 'Aukcje'},
        ),
        migrations.AddField(
            model_name='aukcja',
            name='data_dodania',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aukcja',
            name='stan',
            field=models.CharField(default='Near Mint', max_length=50, verbose_name='Stan karty'),
        ),
        migrations.AlterField(
            model_name='aukcja',
            name='cena_aktualna',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena (PLN)'),
        ),
        migrations.AlterField(
            model_name='aukcja',
            name='kategoria',
            field=models.CharField(choices=[('Mangi', 'Mangi'), ('Gry', 'Gry'), ('Kreskówki', 'Kreskówki'), ('Sport', 'Sport')], max_length=50, verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='aukcja',
            name='rzadkosc',
            field=models.CharField(max_length=50, verbose_name='Rzadkość'),
        ),
        migrations.AlterField(
            model_name='aukcja',
            name='sprzedawca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sprzedający'),
        ),
        migrations.AlterField(
            model_name='aukcja',
            name='tytul',
            field=models.CharField(max_length=200, verbose_name='Tytuł aukcji'),
        ),
    ]
